### ISSUE TITLE
求源码

### ISSUE THREAD

**Issue by huolu1987** [KondeU/CommonSerialRelease#1]
求完整源码，求学习

**Comment by KondeU** [comment]
@huolu1987 已开源在 https://github.com/KondeU/CommonSerial

**Comment by Dufresue** [comment]
您好，可不可以说明一下波形显示那里提示“当前绘图样式不为散点”，“当前样式为：折现”，是什么意思？我打开后看不到波形，是对接受的数据有什么要求吗？

**Comment by KondeU** [comment]
@Dufresue 散点 即绘制的是点（下位机传输来的数据是离散的），折线 即会将绘制的点用线连起来；数据有要求，参考ReadMe中<波形绘制功能的使用>

**Comment by Dufresue** [comment]
我下位机是一直循环printf（“%d.%d”,a,b）到串口上，(a,b是int型)，这算是离散的数据吗？它提示的“当前绘图样式不为散点”意思是它需要下位机发送离散的数据吗？

**Comment by KondeU** [comment]
@Dufresue 不是，不是同一个概念，散点 只是绘图的方式。printf(“%d.%d”,a,b) 数据格式不正确，需要遵守[README.md](https://github.com/KondeU/CommonSerialRelease#readme)中的 接收数据协议（下位机编程协议）。
